# Generated by Django 3.1.2 on 2020-10-17 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import targets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Контент')),
                ('deadline', models.DateField(verbose_name='Дедлайн')),
                ('color', models.CharField(default='#56CCF2', max_length=30, verbose_name='Цвет')),
                ('performance', models.BooleanField(default=False, editable=False, verbose_name='Выполнение')),
                ('photo', models.ImageField(blank=True, upload_to=targets.models.user_directory_path, verbose_name='Фото')),
                ('result', models.IntegerField(default=0, editable=False, verbose_name='Конечный результат')),
                ('result_user', models.IntegerField(default=0, editable=False, verbose_name='Текущий результат')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='targets.progress', verbose_name='Прогресс')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['user'],
            },
        ),
    ]
